using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace ExecPython
{
    class Program
    {
        static void Main(string[] args)
        {

            System.Diagnostics.ProcessStartInfo start = new System.Diagnostics.ProcessStartInfo();
            //python interprater location
            start.FileName = args[0];
            //argument with file name and input parameters
            start.Arguments = string.Format("{0} {1}", args[1],args[2]);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            start.LoadUserProfile = true;
            System.Diagnostics.Process process = System.Diagnostics.Process.Start(start);
            while (true)
            {
                Console.Beep(440,1000);
                System.Threading.Thread.Sleep(1000);
            }
        }
    }
}
